### ISSUE TITLE
Score 5/10

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/exercise-4-innovatech#8]
Improper format
https://github.com/PUP-BSIT/exercise-4-innovatech/blob/a940420a85d52adaea682a8623c34e992337d5b5/src/app/parent/parent.component.ts#L19-L21
It should be 
![image](https://github.com/PUP-BSIT/exercise-4-innovatech/assets/76401444/273925c8-f079-4ac4-b516-8bdbffc87fe7)
minus 1

------

Improper ID naming convention.
https://github.com/PUP-BSIT/exercise-4-innovatech/blob/a940420a85d52adaea682a8623c34e992337d5b5/src/app/parent/parent.component.html#L4
minus 1
https://github.com/PUP-BSIT/exercise-4-innovatech/blob/a940420a85d52adaea682a8623c34e992337d5b5/src/app/parent/parent.component.html#L10
minus 1

-------

Improper indentation
https://github.com/PUP-BSIT/exercise-4-innovatech/blob/a940420a85d52adaea682a8623c34e992337d5b5/src/app/parent/parent.component.html#L22-L48
minus 1

https://github.com/PUP-BSIT/exercise-4-innovatech/blob/a940420a85d52adaea682a8623c34e992337d5b5/src/app/parent/child/child.component.html#L1-L5
minus 1

--------

Score 5/10. You can use a protection card here to reduce deduction. Just take a picture of your protection card and hand it over to me during f2f.

**Comment by Asebuque-ChrystineNoelle** [comment]
This is acknowledged po, sir. We appreciate your feedback and will use it constructively to improve in our future exercises. Thank you po.
